const data = [
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/1.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/2.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/3.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/4.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/5.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/1.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/2.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/3.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/4.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/5.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/1.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/2.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/3.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/4.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore ",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/5.jpg",
  },
];
