export const data = [
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/1.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/2.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/3.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/4.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/5.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/1.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/2.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/3.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/4.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/5.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/1.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/2.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/3.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/4.jpg",
  },
  {
    tieuDe: "NHÀ PHỐ HƯỚNG TÂY, có gác lửng, nội thất mộc mạc",
    noiDung:
      "Ngôi nhà phố hướng Tây với thiết kế gác lửng mang lại sự thông thoáng và tận dụng tối đa không gian sống. Nội thất được thiết kế theo phong cách mộc mạc, sử dụng chất liệu tự nhiên như gỗ và các tông màu ấm áp, tạo cảm giác gần gũi và bình yên.",
    dienTichDat: "100",
    chiPhiThiCong: "900 - 950",
    diaDiem: "Hồ Chí Minh",
    tongDienTichSan: "135",
    dienTichXayDung: "75",
    loaiCongTring: "Nhà Phố",
    namThieKe: "2018",
    img: [
      "/images/maunhadep/nhavuondep/1.jpg",
      "/images/maunhadep/nhavuondep/2.jpg",
      "/images/maunhadep/nhavuondep/3.jpg",
      "/images/maunhadep/nhavuondep/4.jpg",
      "/images/maunhadep/nhavuondep/1.jpg",
    ],
    imgMain: "/images/maunhadep/nhavuondep/5.jpg",
  },
];
